/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsShopRouteImport } from './routes/sports-shop'
import { Route as MusicShopRouteImport } from './routes/music-shop'
import { Route as MedicalStoreRouteImport } from './routes/medical-store'
import { Route as DermatologistClinicRouteImport } from './routes/dermatologist-clinic'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SportsShopRoute = SportsShopRouteImport.update({
  id: '/sports-shop',
  path: '/sports-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicShopRoute = MusicShopRouteImport.update({
  id: '/music-shop',
  path: '/music-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalStoreRoute = MedicalStoreRouteImport.update({
  id: '/medical-store',
  path: '/medical-store',
  getParentRoute: () => rootRouteImport,
} as any)
const DermatologistClinicRoute = DermatologistClinicRouteImport.update({
  id: '/dermatologist-clinic',
  path: '/dermatologist-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/dermatologist-clinic': typeof DermatologistClinicRoute
  '/medical-store': typeof MedicalStoreRoute
  '/music-shop': typeof MusicShopRoute
  '/sports-shop': typeof SportsShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dermatologist-clinic': typeof DermatologistClinicRoute
  '/medical-store': typeof MedicalStoreRoute
  '/music-shop': typeof MusicShopRoute
  '/sports-shop': typeof SportsShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/dermatologist-clinic': typeof DermatologistClinicRoute
  '/medical-store': typeof MedicalStoreRoute
  '/music-shop': typeof MusicShopRoute
  '/sports-shop': typeof SportsShopRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/dermatologist-clinic'
    | '/medical-store'
    | '/music-shop'
    | '/sports-shop'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dermatologist-clinic'
    | '/medical-store'
    | '/music-shop'
    | '/sports-shop'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/dermatologist-clinic'
    | '/medical-store'
    | '/music-shop'
    | '/sports-shop'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  DermatologistClinicRoute: typeof DermatologistClinicRoute
  MedicalStoreRoute: typeof MedicalStoreRoute
  MusicShopRoute: typeof MusicShopRoute
  SportsShopRoute: typeof SportsShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports-shop': {
      id: '/sports-shop'
      path: '/sports-shop'
      fullPath: '/sports-shop'
      preLoaderRoute: typeof SportsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-shop': {
      id: '/music-shop'
      path: '/music-shop'
      fullPath: '/music-shop'
      preLoaderRoute: typeof MusicShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-store': {
      id: '/medical-store'
      path: '/medical-store'
      fullPath: '/medical-store'
      preLoaderRoute: typeof MedicalStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dermatologist-clinic': {
      id: '/dermatologist-clinic'
      path: '/dermatologist-clinic'
      fullPath: '/dermatologist-clinic'
      preLoaderRoute: typeof DermatologistClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  DermatologistClinicRoute: DermatologistClinicRoute,
  MedicalStoreRoute: MedicalStoreRoute,
  MusicShopRoute: MusicShopRoute,
  SportsShopRoute: SportsShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
